### ISSUE TITLE
Class: Base, extensibility bug. __call__() has self reference to public function

### ISSUE THREAD

**Issue by ritualsfinal** [PierreQuentel/PyDbLite#3]
Currently, there is a bug when extending Base.
```
Bug:
return [self[_id] for _id in res]
```
This makes it so that any attempt to rewriting __getitem__() to express another primary key fails.
I noticed you guys were really good about not coupling a lot of your public functions already and I already made a fix from observing that you just used the __getitem__() internal function.
```
Fix:
return [self.records[_id] for _id in res]
```

P.S.
Thanks for the library! It's been really helpful for liteweight projects!

**Comment by PierreQuentel** [comment]
Thanks for the report, I have fixed the bug as you suggested.

It's been a long time since I last worked on PyDbLite so I also fixed a few bugs and made some cleanings in the code.

**Comment by bendikro** [comment]
@ritualsfinal 
I tried to reproduce the issue to create a test for this. Can you give a short example on how to reproduce (for the old version with the bug)?
